# Generated by Django 2.0.7 on 2018-07-14 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blacklist',
            },
        ),
        migrations.CreateModel(
            name='promise',
            fields=[
                ('promid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('mdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('broken', 'Broken'), ('fulfilled', 'Fulfilled'), ('delete', 'Delete')], default='draft', max_length=20)),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('details', models.CharField(max_length=2000)),
                ('compdate', models.DateTimeField(blank=True, null=True)),
                ('promorapprdate', models.DateTimeField(blank=True, null=True)),
                ('promeeapprdate', models.DateTimeField(blank=True, null=True)),
                ('promeeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promeeid', to=settings.AUTH_USER_MODEL)),
                ('promorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promorid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promise',
            },
        ),
    ]
